title: Omar Ayyub
description: A clean, minimal personal site and blog
url: "https://omar.bet"
baseurl: ""

# Author info
author:
  name: Omar Ayyub
  email_name: obayyub
  email_domain: gmail.com
  bio: "A brief intro about yourself that appears at the top of your homepage."

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-feed