title: Omar Ayyub
description: My work and interests.
url: "https://omar.bet"
baseurl: ""

# Author info
author:
  name: Omar Ayyub
  email_name: obayyub
  email_domain: gmail.com
  bio: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-feed